### ISSUE TITLE
'DataFrame' object has no attribute 'Asset' Issue

### ISSUE THREAD

**Issue by GitHackerDoBem** [Jandir/Ativos9x#1]
Traceback (most recent call last):
  File "D:/HackerDoBem/Devs/Trader/Larry.py", line 134, in <module>
    main()
  File "D:/HackerDoBem/Devs/Trader/Larry.py", line 128, in main
    executor.map(AnaliseAtivo, dfSymbols.Asset)
  File "D:\HackerDoBem\Devs\Trader\venv\lib\site-packages\pandas\core\generic.py", line 5139, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'Asset'

**Comment by Jandir** [comment]
Quais versões de bibliotecas está usando? 

O meu pip freeze atual:
certifi==2020.6.20
chardet==3.0.4
idna==2.10
lxml==4.6.1
numpy==1.19.2
pandas==1.1.3
pandas-datareader==0.9.0
python-dateutil==2.8.1
pytz==2020.1
requests==2.24.0
six==1.15.0
urllib3==1.25.11

**Comment by Jandir** [comment]
Verificando aqui o a linha em questão... você já verificou também o conteúdo do 'AtivosB3.csv'? 

O arquivo em questão contém 2 colunas... sendo uma delas o "Asset".

Você pode editá-lo e deixar apenas os ativos que quer rastrear.
